spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mfa_database
    username: mfa_user
    password: 1221
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #ddl-auto: update # Creează/actualizează automat tabelele în baza de date
      ddl-auto: create-drop # Creează tabelele la pornire și le șterge la oprire (util pentru dezvoltare)
    show-sql: true # Îți va arăta în terminal ce query-uri SQL se execută
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect